name: "Variables setup"
description: "Variables setup"

runs:
  using: "composite"
  steps:
    - name: setup variables
      shell: bash
      run: |
        echo "BUILD_OPTS=--configuration=production,e2e" >> $GITHUB_ENV
        echo "TEST_OPTS=" >> $GITHUB_ENV
        echo "E2E_PROTRACTOR_OPTS=" >> $GITHUB_ENV
        echo "E2E_TSCONFIG=tsconfig.e2e.json" >> $GITHUB_ENV
        echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "SMART_RUNNER_DIRECTORY=.protractor-smartrunner" >> $GITHUB_ENV
        echo "BASE_HASH=.protractor-smartrunner" >> $GITHUB_ENV
        echo "HEAD_HASH=HEAD" >> $GITHUB_ENV

    - uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@v1.35.0
    - name: set TAG_NPM
      shell: bash
      run: |
        TAG_NPM="alpha"
        VERSION_IN_PACKAGE_JSON=$(jq -cr '.version' < package.json)

        echo "version in package.json=${VERSION_IN_PACKAGE_JSON}"

        if [[ $BRANCH_NAME =~ ^master(-patch.*)?$ ]]; then
            # Pre-release versions
            if [[ $VERSION_IN_PACKAGE_JSON =~ ^[0-9]*\.[0-9]*\.[0-9]*-A\.[0-9]*$ ]];
            then
                TAG_NPM=next
            # Stable major versions
            else
                TAG_NPM=latest
            fi
        fi

        if [[ $BRANCH_NAME =~ ^develop(-patch.*)?$ ]]; then
            TAG_NPM=alpha
        fi
        echo "TAG_NPM=${TAG_NPM}" >> $GITHUB_ENV
