name: "Variables setup"
description: "Variables setup"

runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/get-commit-message@v1.35.0
    - name: setup variables
      shell: bash
      run: |
        echo "BUILD_OPTS=--configuration=production,e2e" >> $GITHUB_ENV
        echo "TEST_OPTS=" >> $GITHUB_ENV
        echo "E2E_PROTRACTOR_OPTS=" >> $GITHUB_ENV
        echo "E2E_TSCONFIG=tsconfig.e2e.json" >> $GITHUB_ENV
        echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "SMART_RUNNER_DIRECTORY=.protractor-smartrunner" >> $GITHUB_ENV
        echo "BASE_HASH=.protractor-smartrunner" >> $GITHUB_ENV
        echo "HEAD_HASH=HEAD" >> $GITHUB_ENV
    - name: setup branch name
      shell: bash
      run: |
        export BRANCH_NAME=""
        if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH_NAME=${GITHUB_REF##*/}
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME=${GITHUB_BASE_REF}
        fi
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
    - name: set TAG_NPM
      shell: bash
      run: |
        VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json')".version)
        echo "version in package.json=${VERSION_IN_PACKAGE_JSON}"
        if [[ $BRANCH_NAME =~ ^master(-patch.*)?$ ]]; then
            # Pre-release versions
            if [[ $VERSION_IN_PACKAGE_JSON =~ ^[0-9]*\.[0-9]*\.[0-9]*-A\.[0-9]*$ ]];
            then
                TAG_NPM=next
            # Stable major versions
            else
                TAG_NPM=latest
            fi
        fi
        if [[ $BRANCH_NAME =~ ^develop(-patch.*)?$ ]]; then
            TAG_NPM=alpha
        fi
        echo "TAG_NPM=${TAG_NPM}" >> $GITHUB_ENV
