name: "Publish Docker Images"
description: "Publish Docker Image to the provided registry"

inputs:
  registry:
    description: 'Docker registry'
    required: true
    type: string
  username:
    description: 'login username'
    required: true
    type: string
  password:
    description: 'login password'
    required: true
    type: string
  branch_name:
    description: 'Name of the branch the workflow runs on'
    required: true
    type: string
  dry-run:
    description: dry run flag
    required: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Get Tag
      uses: ./.github/actions/get-image-tag
      with:
        branch_name: ${{ inputs.branch_name }}

    - name: Install dependencies and build project
      shell: bash
      run: |
        npm ci
        npm run build.release

    - name: Build and push multi-platform image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event.inputs.dry-run != 'true' }}
        tags: ${{ inputs.registry }}/alfresco/alfresco-content-app:${{ env.TAG_VERSION }}
