name: "After e2e"
description: "After e2e"

env:
  storage_file: "./storage-state/AdminUserState.json"

inputs:
  id:
    description: 'test suite id'
    required: true
    type: number


runs:
  using: "composite"
  steps:
    - name: Remove storage file
      shell: bash
      run: rm -f ${{ env.storage_file }}

    - name: Upload protractor-smartrunner artifact related to this particular job to S3
      uses: ./.github/actions/upload-job-artifact
      with:
        artifact: $SMART_RUNNER_DIRECTORY
        output: $S3_DBP_FOLDER/protractor-smartrunner-${{ github.run_id }}-${{ inputs.id }}.tar.bz2
