name: "Before install and variables setup"
description: "Before install and variables setup"

inputs:
  artifact:
    description: 'path to the artifact to archieve (tar.bz2) and upload (like ./dist)'
    required: true
    type: string
  output:
    description: 'the S3 object to copy it to, like: s3://bucket-name/folder/whatever.tar.bz2'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: setup variables
      shell: bash
      run: |
        echo "BUILD_OPTS=--configuration=production,e2e" >> $GITHUB_ENV
        echo "TEST_OPTS=" >> $GITHUB_ENV
        echo "E2E_PROTRACTOR_OPTS=" >> $GITHUB_ENV
        echo "E2E_TSCONFIG=tsconfig.e2e.json" >> $GITHUB_ENV
        export HEAD_COMMIT_HASH="${GITHUB_HEAD_REF}:-${GITHUB_SHA}"
        export COMMIT_MESSAGE=`git log --format=%B -n 1 $HEAD_COMMIT_HASH`
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "SMART_RUNNER_DIRECTORY=.protractor-smartrunner" >> $GITHUB_ENV
        echo "BASE_HASH=.protractor-smartrunner" >> $GITHUB_ENV
        echo "HEAD_HASH=HEAD" >> $GITHUB_ENV
    - name: setup S3 caching
      shell: bash
      run: |
        pip install -q awscli
        S3_DBP_PATH="s3://alfresco-travis-builds/aca"
        if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH_NAME=${GITHUB_REF##*/}
            S3_DBP_ROOT_FOLDER="$S3_DBP_PATH/$BRANCH_NAME"
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME=${GITHUB_BASE_REF}
            S3_DBP_ROOT_FOLDER="$S3_DBP_PATH/$BRANCH_NAME"
            echo "BASE_HASH=origin/$BRANCH_NAME" >> $GITHUB_ENV
        elif [ "${TRAVIS_EVENT_TYPE}" == "schedule" ]; then
            S3_DBP_ROOT_FOLDER="$S3_DBP_PATH/cron"
        else
            S3_DBP_ROOT_FOLDER="$S3_DBP_PATH/api"
        fi
        echo "S3_DBP_FOLDER="$S3_DBP_ROOT_FOLDER/${{ github.run_id }}"" >> $GITHUB_ENV
    - name: ADF linking
      if: ${{ github.event_name == 'pull_request'}}
      uses: ./.github/actions/adf-linking
      with:
        commit-message: $COMMIT_MESSAGE
