version: 2

jobs:
  test:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test:ci
  lint:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
  spellcheck:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run spellcheck
  build:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - lint:
          requires:
            - test
      - spellcheck:
          requires:
            - test
      - build:
          requires:
            - test
