version: 2
jobs:
  build:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test:ci
