version: 2

jobs:
  install:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  lint:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
  test:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: xvfb-run -a npm run test:ci
  build:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
  e2e:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install && npm run build
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: npm run e2e:docker

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - e2e:
          requires:
            - lint
            - test
            - build
