version: 2

jobs:
  install:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  lint:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: ng lint
  test:
    working_directory: ~/alfresco-content-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: alfresco-content-app-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: xvfb-run -a npm run test:ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
