name: Deploy local ACS for E2E testing

inputs:
  docker_username:
    description: 'Docker username'
    required: true
  docker_password:
    description: 'Docker password'
    required: true
  quay_username:
    description: 'Quay username'
    required: true
  quay_password:
    description: 'Quay password'
    required: true

runs:
  using: "composite"
  steps:
    - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814
      with:
        version: "3.14.3"

    - name: Login to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Login to Quay.io
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
      with:
        registry: quay.io
        username: ${{ inputs.quay_username }}
        password: ${{ inputs.quay_password }}

    - name: Setup cluster
      uses: Alfresco/alfresco-build-tools/.github/actions/setup-kind@v8.4.0
      with:
        ingress-nginx-ref: controller-v1.8.2
        metrics: "true"

    - name: Set nginx ingress config
      shell: bash
      run: >-
        kubectl -n ingress-nginx patch cm ingress-nginx-controller
        -p '{"data": {"allow-snippet-annotations":"true"}}'

    - name: Create registries auth secret
      shell: bash
      run: >-
        kubectl create secret generic regcred
        --from-file=.dockerconfigjson=$HOME/.docker/config.json
        --type=kubernetes.io/dockerconfigjson

    # to be skipped imo
    # - name: Check if cgroup v2 workaround is needed
    #   if: startsWith(matrix.values, '7.')
    #   env:
    #     VALUES_FILE: ${{ matrix.values }}
    #   id: cgroupv2-workaround-extra-values
    #   run: |
    #     if [ ${VALUES_FILE:2:1} -le 2 ]; then
    #       echo "Enabling cgroupv v2 workaround"
    #       echo "helm_install_params=--values test/cgroup-v2-workaround-values.yaml" >> "$GITHUB_OUTPUT"
    #     fi

    # - name: Check if we want additional helm customizations
    #   id: configurable-extra-values
    #   run: |
    #     if [ "${{ matrix.values }}" = "pre-release_values.yaml" ] || [ "${{ matrix.values }}" = "values.yaml" ]; then
    #       echo "Enabling clustered tests with 2 replicas"
    #       echo "helm_install_params=--set alfresco-repository.replicaCount=2" >> "$GITHUB_OUTPUT"
    #     fi

    - name: Add dependency chart repos
      shell: bash
      run: |
        helm repo add self https://alfresco.github.io/alfresco-helm-charts/
        helm repo add elastic https://helm.elastic.co/

    - name: Checkout acs-deployment sources
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: Alfresco/acs-deployment
        ref: v8.6.1
        path: acs-deployment

    # Name and value to be fetched by automation??
    - name: Helm install
      shell: bash
      run: >-
        helm dep build acs-deployment/helm/alfresco-content-services &&
        helm install acs acs-deployment/helm/alfresco-content-services
        --set global.search.sharedSecret="$(openssl rand -hex 24)"
        --set global.known_urls=http://localhost
        --set global.alfrescoRegistryPullSecrets=regcred
        --values acs-deployment/test/enterprise-integration-test-values.yaml

    - name: Watch Helm deployment
      shell: bash
      run: |
        kubectl get pods --watch &
        KWPID=$!
        kubectl wait --timeout=7m --all=true --for=condition=Available deploy && kill $KWPID
        echo -n "Waiting for ESC Reindexing job to complete... "
        kubectl wait --timeout=5m --for=condition=complete job/acs-alfresco-search-enterprise-reindexing
        echo "Completed."

    - name: Spit cluster status after install
      if: always()
      shell: bash
      run: |
        helm ls --all-namespaces --all
        helm status acs --show-resources
        kubectl describe pod
        curl -vL http://localhost
