#!/usr/bin/env bash
#
# Resolve the latest available image tags for the ACS stack and emit a Helm
# values override file.
#
# This mirrors the "always latest" behaviour of the Flux acadev environment
# (apps/base/git-acs + apps/base/automation/image-policies in the
# flux-alfresco-pipeline repo), where each component image is continuously
# bumped to the newest tag matching its policy. Flux image-automation cannot run
# inside the ephemeral CI kind cluster, so instead we query the registry at
# deploy time and pick the newest matching tag for every component.
#
# Usage:
#   fetch-latest-acs-images.sh <output-values-file>
#
# Requires: skopeo, jq. Registry auth is taken from the Docker config populated
# by the `docker login` steps in the calling action.

set -euo pipefail

OUTPUT_FILE="${1:-acs-latest-images-values.yaml}"
AUTHFILE="${HOME}/.docker/config.json"
REGISTRY="quay.io/alfresco"

# Tag filter patterns, matching the Flux ImagePolicy `filterTags.pattern` values.
# Most components track alpha builds (e.g. 5.5.0-A.1); the client apps track
# GA-style tags (e.g. 7.5.0-27187417103).
A_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+-A\.[0-9]+$'
GA_PATTERN='^([0-9]+\.){2}[0-9]+(-[0-9]+)?$'

# latest_tag <image> <pattern>
# Prints the newest tag of quay.io/alfresco/<image> matching <pattern>.
latest_tag() {
  local image="$1" pattern="$2" tags tag
  tags="$(skopeo list-tags --authfile "${AUTHFILE}" "docker://${REGISTRY}/${image}" \
    | jq -r '.Tags[]')"

  tag="$(printf '%s\n' "${tags}" | grep -E "${pattern}" | sort -V | tail -n1 || true)"

  if [ -z "${tag}" ]; then
    echo "ERROR: no tag matching '${pattern}' found for ${REGISTRY}/${image}" >&2
    return 1
  fi
  echo "${tag}"
}

echo "Resolving latest ACS image tags from ${REGISTRY} ..." >&2

# --- Repository / Share (all-amps pipeline builds) ---
REPO_TAG="$(latest_tag alfresco-pipeline-all-amps-repo "${A_PATTERN}")"
SHARE_TAG="$(latest_tag alfresco-pipeline-all-amps-share "${A_PATTERN}")"

# --- Connectors / AI ---
AI_TAG="$(latest_tag alfresco-ai-docker-engine "${A_PATTERN}")"
OOI_TAG="$(latest_tag alfresco-ooi-service "${A_PATTERN}")"
TEAMS_TAG="$(latest_tag alfresco-ms-teams-service "${A_PATTERN}")"

# --- Client apps (GA-style tags) ---
CONTROL_CENTER_TAG="$(latest_tag alfresco-control-center "${GA_PATTERN}")"
DIGITAL_WORKSPACE_TAG="$(latest_tag alfresco-digital-workspace "${GA_PATTERN}")"

# --- Search ---
SEARCH_SERVICES_TAG="$(latest_tag search-services "${A_PATTERN}")"
ES_MEDIATION_TAG="$(latest_tag alfresco-elasticsearch-live-indexing-mediation "${A_PATTERN}")"
ES_CONTENT_TAG="$(latest_tag alfresco-elasticsearch-live-indexing-content "${A_PATTERN}")"
ES_METADATA_TAG="$(latest_tag alfresco-elasticsearch-live-indexing-metadata "${A_PATTERN}")"
ES_PATH_TAG="$(latest_tag alfresco-elasticsearch-live-indexing-path "${A_PATTERN}")"
ES_REINDEX_TAG="$(latest_tag alfresco-elasticsearch-reindexing "${A_PATTERN}")"

# --- Transform pipeline ---
TRANSFORM_ROUTER_TAG="$(latest_tag alfresco-transform-router "${A_PATTERN}")"
PDF_RENDERER_TAG="$(latest_tag alfresco-pdf-renderer "${A_PATTERN}")"
IMAGEMAGICK_TAG="$(latest_tag alfresco-imagemagick "${A_PATTERN}")"
LIBREOFFICE_TAG="$(latest_tag alfresco-libreoffice "${A_PATTERN}")"
TIKA_TAG="$(latest_tag alfresco-tika "${A_PATTERN}")"
TRANSFORM_MISC_TAG="$(latest_tag alfresco-transform-misc "${A_PATTERN}")"
SHARED_FILE_STORE_TAG="$(latest_tag alfresco-shared-file-store "${A_PATTERN}")"

# --- Sync / Audit / Knowledge retrieval ---
SYNC_TAG="$(latest_tag service-sync "${A_PATTERN}")"
AUDIT_TAG="$(latest_tag alfresco-audit-storage "${A_PATTERN}")"
HXI_INGESTER_TAG="$(latest_tag alfresco-hxinsight-connector-live-ingester "${A_PATTERN}")"

cat > "${OUTPUT_FILE}" <<EOF
# Generated by fetch-latest-acs-images.sh - do not edit by hand.
# Pins every ACS component to the newest available image tag so that ACA e2e
# tests run against the same "latest" backend as the Flux acadev environment.
alfresco-repository:
  image:
    repository: ${REGISTRY}/alfresco-pipeline-all-amps-repo
    tag: ${REPO_TAG}
share:
  image:
    repository: ${REGISTRY}/alfresco-pipeline-all-amps-share
    tag: ${SHARE_TAG}
alfresco-ai-transformer:
  image:
    repository: ${REGISTRY}/alfresco-ai-docker-engine
    tag: ${AI_TAG}
alfresco-connector-ms365:
  image:
    repository: ${REGISTRY}/alfresco-ooi-service
    tag: ${OOI_TAG}
alfresco-connector-msteams:
  image:
    repository: ${REGISTRY}/alfresco-ms-teams-service
    tag: ${TEAMS_TAG}
alfresco-control-center:
  image:
    repository: ${REGISTRY}/alfresco-control-center
    tag: ${CONTROL_CENTER_TAG}
alfresco-digital-workspace:
  image:
    repository: ${REGISTRY}/alfresco-digital-workspace
    tag: ${DIGITAL_WORKSPACE_TAG}
alfresco-search:
  searchServicesImage:
    repository: ${REGISTRY}/search-services
    tag: ${SEARCH_SERVICES_TAG}
alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        repository: ${REGISTRY}/alfresco-elasticsearch-live-indexing-mediation
        tag: ${ES_MEDIATION_TAG}
    content:
      image:
        repository: ${REGISTRY}/alfresco-elasticsearch-live-indexing-content
        tag: ${ES_CONTENT_TAG}
    metadata:
      image:
        repository: ${REGISTRY}/alfresco-elasticsearch-live-indexing-metadata
        tag: ${ES_METADATA_TAG}
    path:
      image:
        repository: ${REGISTRY}/alfresco-elasticsearch-live-indexing-path
        tag: ${ES_PATH_TAG}
  reindexing:
    image:
      repository: ${REGISTRY}/alfresco-elasticsearch-reindexing
      tag: ${ES_REINDEX_TAG}
alfresco-transform-service:
  transformrouter:
    image:
      repository: ${REGISTRY}/alfresco-transform-router
      tag: ${TRANSFORM_ROUTER_TAG}
  pdfrenderer:
    image:
      repository: ${REGISTRY}/alfresco-pdf-renderer
      tag: ${PDF_RENDERER_TAG}
  imagemagick:
    image:
      repository: ${REGISTRY}/alfresco-imagemagick
      tag: ${IMAGEMAGICK_TAG}
  libreoffice:
    image:
      repository: ${REGISTRY}/alfresco-libreoffice
      tag: ${LIBREOFFICE_TAG}
  tika:
    image:
      repository: ${REGISTRY}/alfresco-tika
      tag: ${TIKA_TAG}
  transformmisc:
    image:
      repository: ${REGISTRY}/alfresco-transform-misc
      tag: ${TRANSFORM_MISC_TAG}
  filestore:
    image:
      repository: ${REGISTRY}/alfresco-shared-file-store
      tag: ${SHARED_FILE_STORE_TAG}
alfresco-sync-service:
  image:
    repository: ${REGISTRY}/service-sync
    tag: ${SYNC_TAG}
alfresco-audit-storage:
  image:
    repository: ${REGISTRY}/alfresco-audit-storage
    tag: ${AUDIT_TAG}
alfresco-knowledge-retrieval:
  liveIngester:
    image:
      repository: ${REGISTRY}/alfresco-hxinsight-connector-live-ingester
      tag: ${HXI_INGESTER_TAG}
  repository:
    versionOverride: ${REPO_TAG}
EOF

echo "Wrote resolved image tags to ${OUTPUT_FILE}:" >&2
cat "${OUTPUT_FILE}" >&2
