name: "Update Library Versions"
description: "Updates ACA libraries according to the root Version"

inputs:
  dry-run:
    description: dry run flag
    required: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Update Versions
      shell: bash
      run: |
        VERSION_IN_PACKAGE_JSON=$(jq -cr '.version' < package.json)

        if [[ ${{ inputs.branch_name }} =~ ^master.*?$ ]] ; then
          NEW_LIBRARY_VERSION="$VERSION_IN_PACKAGE_JSON"
        else
          NEW_LIBRARY_VERSION="${VERSION_IN_PACKAGE_JSON}-${{ github.run_id }}"
        fi

        ./scripts/gh/update-lib-versions.sh "$NEW_LIBRARY_VERSION" "${{ inputs.dry-run }}"

        echo "Building projects"
        npm run build-libs
