name: "Download build artifacts"
description: "Download build artifacts"

inputs:
  artifact:
    description: 'path to the s3 artifact (tar.bz2) to download and extract'
    required: true
    type: string
  output:
    description: 'directory to extract the archive to'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ AWS_DEFAULT_REGION }}
    - name: download build artifacts from s3
      shell: bash
      run: |
        test ! -d ${{ inputs.output }} && mkdir -p ${{ inputs.output }}
        aws s3 cp ${{ inputs.artifact }} ./s3-artifact.tmp
        echo 'artifact download done'
        tar -xvf ./s3-artifact.tmp -C ${{ inputs.output }} >&/dev/null
        echo 'tar the artifact done'
        rm ./s3-artifact.tmp
        echo 'remove tmp file'
