name: "ADF linking"
description: "ADF linking"

runs:
  using: "composite"
  steps:
    - name: clone and install
      shell: bash
      run: |
        echo "${{ env.COMMIT_MESSAGE }}"
        echo "${{ COMMIT_MESSAGE }}"
        if [[ ${{ env.COMMIT_MESSAGE }} == *"[link-adf:"* ]]; then
            echo "BUILD_OPTS=--configuration=adfprod,e2e" >> $GITHUB_ENV
            echo "TEST_OPTS=--configuration=adfprod" >> $GITHUB_ENV
            echo "E2E_PROTRACTOR_OPTS=--with-local-adf" >> $GITHUB_ENV
            echo "E2E_TSCONFIG=tsconfig.e2e.adf.json" >> $GITHUB_ENV
            BRANCH=`echo ${{ env.COMMIT_MESSAGE }} | grep -o "\[link-adf\:[^]]*\]" | sed -e 's#\[link-adf:##g' | sed -e 's#\]##g'`
            echo "Checking out ADF's branch: ${BRANCH}" && \
            git clone https://github.com/Alfresco/alfresco-ng2-components.git --depth=1 --branch ${BRANCH} ../alfresco-ng2-components
        else
            echo -e "\e[32mUsing ADF from installed node_modules.\e[0m"
        fi ;
