name: "Cron multibrowser E2E runs"

on:
  schedule:
    - cron: '0 6 * * 1-5' #At 06:00 on every day-of-week from Monday through Friday.

jobs:
  chrome:
    name: "Cron browser E2E run - chrome"
    uses: ./.github/workflows/e2e-playwright-reusable.yml
    with:
      browser: chrome
    secrets:
      SCREENSHOT_USERNAME: ${{ secrets.SCREENSHOT_USERNAME }}
      SCREENSHOT_PASSWORD: ${{ secrets.SCREENSHOT_PASSWORD }}
      REPORT_PORTAL_URL: ${{ secrets.REPORT_PORTAL_URL }}
      REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  firefox:
    name: "Cron browser E2E run - firefox"
    needs: chrome
    if: ${{ always() }}
    uses: ./.github/workflows/e2e-playwright-reusable.yml
    with:
      browser: firefox
    secrets:
      SCREENSHOT_USERNAME: ${{ secrets.SCREENSHOT_USERNAME }}
      SCREENSHOT_PASSWORD: ${{ secrets.SCREENSHOT_PASSWORD }}
      REPORT_PORTAL_URL: ${{ secrets.REPORT_PORTAL_URL }}
      REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  webkit:
    name: "Cron browser E2E run - webkit"
    needs: firefox
    if: ${{ always() }}
    uses: ./.github/workflows/e2e-playwright-reusable.yml
    with:
      browser: webkit
    secrets:
      SCREENSHOT_USERNAME: ${{ secrets.SCREENSHOT_USERNAME }}
      SCREENSHOT_PASSWORD: ${{ secrets.SCREENSHOT_PASSWORD }}
      REPORT_PORTAL_URL: ${{ secrets.REPORT_PORTAL_URL }}
      REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  msedge:
    name: "Cron browser E2E run - msedge"
    needs: webkit
    if: ${{ always() }}
    uses: ./.github/workflows/e2e-playwright-reusable.yml
    with:
      browser: msedge
    secrets:
      SCREENSHOT_USERNAME: ${{ secrets.SCREENSHOT_USERNAME }}
      SCREENSHOT_PASSWORD: ${{ secrets.SCREENSHOT_PASSWORD }}
      REPORT_PORTAL_URL: ${{ secrets.REPORT_PORTAL_URL }}
      REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
