name: "Daily CI pipeline cron"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5' #At 12:00 on every day-of-week from Monday through Friday.

env:
  BASE_URL: ${{ secrets.PIPELINE_ENV_URL }}
  ADMIN_EMAIL: ${{ secrets.PIPELINE_ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.PIPELINE_ADMIN_PASSWORD }}
  HR_USER: ${{ secrets.HR_USER }}
  HR_USER_PASSWORD: ${{ secrets.HR_USER_PASSWORD }}
  SCREENSHOT_USERNAME: ${{ secrets.SCREENSHOT_USERNAME }}
  SCREENSHOT_PASSWORD: ${{ secrets.SCREENSHOT_PASSWORD}}
  PLAYWRIGHT_E2E_HOST: ${{ secrets.PLAYWRIGHT_E2E_HOST }}
  GH_BUILD_NUMBER: ${{ github.run_id }}
  REPORT_PORTAL_URL: ${{ secrets.REPORT_PORTAL_URL }}
  REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
  MAXINSTANCES: 2
  RETRY_COUNT: 2

jobs:
  run-e2e:
    name: Run e2e
    uses: ./.github/workflows/pull-request.yml
    with:
      cron-run: 'true'
    secrets: inherit
